#!/usr/bin/env zsh
echo $(urf_bold "Installing programs...")

if urf_yNprompt "Update System? (Y/n)"; then
    urf_upgrade
fi

case $WHARDWARE in
    (Darwin*)
        # if [ ! -d ~/.oh-my-zsh ]; then
        #     echo $(urf_bold "Installing OMZ in seperate window...")
        #     osascript -e 'tell application "Terminal" to do script "sh -c \"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\""'
        # fi

        if [ ! "$(mas account)" = "er.burnell@gmail.com" ]; then
	          mas signin er.burnell@gmail.com
        fi

        if urf_yNprompt "Update System? (Y/n)"; then
	          echo $(urf_bold "Ensuring Cellar is fully stocked...")
	          local wbrewfile=$(urf_repofile Brewfile)
	          if ! urf_contains "$(brew bundle check --file=$wbrewfile)" "dependencies are satisfied"; then
	              brew bundle -v --file=$wbrewfile
	          fi
        fi
        
        # Magnet
        #mas install 441258766 &>/dev/null
        ;;
    (Linux*)
        source functions-linux

        install_layers
        ;|
(Linux-x86*)
        # SOFTWARE_DIR=~/Downloads
        # if ! isinstalled google-chrome; then
        #     wget -P /tmp/ https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #     installdeb "google-chrome-stable" /tmp/google-chrome-stable_current_amd64.deb
        #     rm -rf /tmp/google-chrome-stable_current_amd64.deb*
        # fi
        # Could simplify this, place the find inside installdeb if needed
        # installdeb "google-chrome-stable" $SOFTWARE_DIR/google-chrome-stable_current_amd64.deb
        # installdeb "steam-launcher" $SOFTWARE_DIR/steam_latest.deb
        # installjide "pycharm" $SOFTWARE_DIR bin/pycharm.sh
        # installjide "ideaIU" $SOFTWARE_DIR bin/idea.sh
        # installeclipse "eclipse-inst" $SOFTWARE_DIR eclipse-inst
        # unset SOFTWARE_DIR
esac

# Install Oh My ZSH without changing shell or running zsh, since we already have it set up.
if [ ! -d ~/.oh-my-zsh ]; then
    echo $(urf_bold "Ensuring Oh-My-ZSH is operational...")
    wget -P /tmp/ https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh
    sed -i.tmp 's:env zsh::g' /tmp/install.sh
    sed -i.tmp 's:chsh -s .*$::g' /tmp/install.sh
    sh /tmp/install.sh   
    chsh -s $(which zsh) $(whoami)
fi
